# Lang
language: zh

# Dark Mode
dark: false

# Header
menu:
  Home: /
  Blog: /archives
  Contact: /contact
  Links: /links
  RSS: /atom.xml

# Content
fancybox: true


# Miscellaneous
google_analytics:
favicon: /pics/n0vad3v.jpg
twitter:
google_plus:
fb_admins:
fb_app_id:


# Profile
nickname: N0vaD3v's Awesome Blog
description: 43EC 6073 0BFF A16C 34BB 9EF2 8D42 A0E6 99E5 0639
links:
  BLOG: /archives
  GITHUB: https://github.com/n0vad3v
  TWITTER: https://twitter.com/n0vad3v
  PORTFILOS: https://500px.com/n0vad3v
  CONTACT: /contact


# Info
archive_footer_content: <b>如未特殊声明，本站所有文章采用<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></b>
post_footer_content: <b>如未特殊声明，本站所有文章采用<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></b>
